### ISSUE TITLE
Create login simple login page

### ISSUE THREAD

**Issue by JoinHiddleston** [JoinHiddleston/sales-management-system#1]
I need to create a simple login page. Create a simple function that displays a message as a username.

**Comment by HaoHuynh0301** [comment]
Hi ! I think I can solve this issue. Can you assign this for me ? Thank you @JoinHiddleston

**Comment by JoinHiddleston** [comment]
Go for it @HaoHuynh0301

**Comment by henryjohn1011** [comment]
assign me. i can solve it.

**Comment by vonet999** [comment]
assign me. i can solve it.
